### ISSUE TITLE
How exactly do I run this tool?

### ISSUE THREAD

**Issue by Vibhav201** [Aonodensetsu/prev_gen#1]
I am on openSUSE Tumbleweed and I am not able to run this tool.
1. I ran `pip install prev_gen` but got `error: externally-managed-environment`
2. Then, I tried with `pipx install --verbose --include-deps prev-gen` and this time I got something.
```
installed package prev-gen 4.5.1, installed using Python 3.11.5
  These apps are now globally available
    - get_gprof
    - get_objgraph
    - tqdm
    - undill
done! ✨ 🌟 ✨
```
3. I don't know what to do next. Sorry if I am being stupid. The command prev-gen is still not available to run. I tried some other things but failed to run this tool.

I would really appreciate some details on how can i use this amazing tool.

**Comment by Aonodensetsu** [comment]
1. the first error has to do with your environment, due to the way linux package managers work, pip will not allow a global installation since a few releases ago in order to not clobber the state for whatever other managers may be installed

to overcome it you can use `--break-system-packages` (which is as bad an idea as the name suggests) or install the package inside a virtual environment (alternatively you can `zypper in python3-<package name on PyPi>` for some common packages)
```bash
zypper in python3-virtualenv / pip install virtualenv # installs the necessary package
python -m venv .venv # makes the virtual environment folder
.venv/Scripts/activate # enters the virtual environment
pip install prev_gen # any packages installed here will not break your system
python my_script.py # any other commands will run inside the environment
deactivate # go back to regular environment
```
virtual environments are a common and well-liked way to separate python dependencies, you can make a virtualenv for each specific project and it makes sure that the dependencies are in a separated and controlled state, since you don't need to ensure all projects work with the same version of what you have installed

2. pipx is smarter than pip, supposedly, but i never used it, since i have every single project in a separate virtual environment, with a few exceptions

3. this package is not a command, it's a python library - there is no command line tool available for it (yet)

to run it, make a file [like the example](https://github.com/Aonodensetsu/prev_gen/blob/main/example.py), and simply run it as you would any other python script using `python filename.py`, the important bit is [here](https://github.com/Aonodensetsu/prev_gen/blob/main/example.py#L52) and [here](https://github.com/Aonodensetsu/prev_gen#usage) (i updated the README to specify it's inside a python file)

**Comment by Vibhav201** [comment]
Hi, Thanks for the inputs, now I did the steps to create and activate the virtual enviroment and ran the example.py file, and I was able to get the output. Thanks for this amazing tool. But, I wish this tool could be run as a GUI. I will be generating files for all my favourite colour schemes from this (Dracula, Catppuccin, Gruvbox Material, Everforest, Sonokai). Thanks again.

**Comment by Aonodensetsu** [comment]
Also, gruvbox material already has a preview made with (an old version of) this since it's the reason i made this tool in the first place

**Comment by Aonodensetsu** [comment]
@Vibhav201 a cli tool was added along with yaml, json and toml support

**Comment by Vibhav201** [comment]
That's just amazing. It's complete now. Thanks :)

I also have created an interesting tool with my almost non-existent scripting knowledge recently, checkout my pinned repo.
